import fs from 'node:fs';
import assert from 'node:assert/strict';
import * as THREE from '../dist/vendor/three.module.js';
import {createWorld,stepVehicle,nearestSegment,inPolygon} from '../dist/physics.js';
import {createCity} from '../dist/city.js';
const data=JSON.parse(fs.readFileSync(new URL('../dist/data/east-village.json',import.meta.url)));
const start=performance.now();
const world=createWorld(data);
assert.equal(inPolygon(5,5,[[0,0],[10,0],[10,10],[0,10]]),true);
assert.equal(inPolygon(15,5,[[0,0],[10,0],[10,10],[0,10]]),false);
assert.equal(nearestSegment(5,5,[0,0],[10,0]).d,5);
const spawn=world.spawn((-73.9836-data.origin[1])*data.scale,-(40.7266-data.origin[0])*111320);
assert.ok(!world.carCollides(spawn.x,spawn.z,spawn.yaw),'initial spawn is clear');
console.log('Start street:',spawn.road.name,'coordinates:',spawn.x.toFixed(2),spawn.z.toFixed(2));
const landmarks=['Veselka',"Katz's Delicatessen",'Strand Bookstore',"McSorley's Old Ale House"];
for(const name of landmarks){const p=data.places.find(p=>p.name===name);assert.ok(p,name);const s=world.spawn(...p.p);assert.ok(!world.carCollides(s.x,s.z,s.yaw),'clear landmark arrival: '+name);}
const empty={carCollides:()=>false};let vehicle={x:0,z:0,yaw:0,speed:0,steer:0};
for(let i=0;i<180;i++)stepVehicle(vehicle,{forward:true},1/60,empty,[-10000,-10000,10000,10000]);assert.ok(vehicle.speed>15&&vehicle.z<-20,'accelerates and moves north');
for(let i=0;i<240;i++)stepVehicle(vehicle,{brake:true},1/60,empty,[-10000,-10000,10000,10000]);assert.equal(vehicle.speed,0,'brakes to stop');
for(let i=0;i<90;i++)stepVehicle(vehicle,{reverse:true},1/60,empty,[-10000,-10000,10000,10000]);assert.ok(vehicle.speed<0,'reverse works');
vehicle={x:0,z:0,yaw:0,speed:10,steer:0};stepVehicle(vehicle,{left:true},1/60,empty,[-100, -100,100,100]);assert.ok(vehicle.yaw<0,'left steers west');
vehicle={x:0,z:0,yaw:0,speed:10,steer:0};const collision=stepVehicle(vehicle,{forward:true},1/60,{carCollides:()=>true},[-100,-100,100,100]);assert.ok(collision.collision);assert.equal(vehicle.x,0);assert.equal(vehicle.z,0);assert.equal(vehicle.speed,0);
vehicle={x:0,z:-84.99,yaw:0,speed:10,steer:0};assert.ok(stepVehicle(vehicle,{forward:true},1/60,empty,[-100,-100,100,100]).edge,'boundary blocks leaving map');
console.log('Physics and all featured landmark arrivals passed.');
const scene=new THREE.Scene();const city=createCity(scene,data,world);let vertices=0,triangles=0;
scene.traverse(obj=>{if(!obj.geometry)return;const g=obj.geometry,p=g.attributes.position;vertices+=p.count;triangles+=(g.index?g.index.count:p.count)/3*(obj.count||1);assert.ok(p.array.every(Number.isFinite),'finite vertices');if(g.index)assert.ok(g.index.array.every(i=>i<p.count),'valid indices');});
assert.ok(city.buildingMeshes.length>10);assert.ok(city.trees>100);
console.log(JSON.stringify({objects:scene.children.length,buildingChunks:city.buildingMeshes.length,trees:city.trees,vertices,triangles,seconds:((performance.now()-start)/1000).toFixed(1)}));
const shader={uniforms:{},vertexShader:'#include <common>\n#include <begin_vertex>',fragmentShader:'#include <common>\n#include <color_fragment>'};city.buildingMat.onBeforeCompile(shader);assert.ok(shader.vertexShader.includes('vCityUv=uv'));assert.ok(shader.fragmentShader.includes('float window='));
console.log('Full city geometry validated.');
